MVCWeb/Controllers/DefaultController.cs
using MVCWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MVCWeb.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            var list = new List<Item>();
            list.Add(new Item { Id=1});
            list.Add(new Item { Id = 2 });
            list.Add(new Item { Id = 3 });
            list.Add(new Item { Id = 4 });

            return View(list);
        }
        public ActionResult MainView()
        {
            ViewBag.SendCodeViewModel = 1;
            ViewBag.SendCodeViewModel1 = 2;
            return View();
        }
        public ActionResult DateModel()
        {            
            return View();
        }
        [HttpPost]
        public ActionResult commanPartial()
        {
            ViewBag.Name = Request["text"].ToString();
            return View("addComment");
        }
        [HttpGet]
        public ActionResult addComment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addCommentPost()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DateModel(CustomerAccount ca)
        {
            //CustomerAccount ca = new CustomerAccount();
            ca.DOB = DateTime.Now;
            return View(ca);
        }
        public ActionResult updatevat(int ID, bool status)
        {
            //Cust_Det e = (from e1 in db.Cust_Det

            //              where e1.Cust_Acc_No == ID

            //              select e1).First();

            //e.VAT_Exempt = status;

            //db.SaveChanges();
            return RedirectToAction(null, new RouteValueDictionary(new { controller = "Customer", action = "Index", store_id = -1 }));

        }

        public ActionResult updatdisc(int ID, int discuount)
        {
            //Cust_Det e = (from e1 in db.Cust_Det

            //              where e1.Cust_Acc_No == ID

            //              select e1).First();

            //e.Disc_Level = discuount;

            //db.SaveChanges();


            return RedirectToAction(null, new RouteValueDictionary(new { controller = "Customer", action = "Index", store_id = -1 }));

        }
        public ActionResult Edit(CustomerAccount model)
        {
            model=new CustomerAccount { ID = 1, Is_Biz_Cust = true, Email = "123", Full_Name = "test1" };
            //var custdetail = new MVCWeb.Models.DefaultModel.custdetail() { Company_Email="test", Company_Name="test2"};
            return View(model);
        }
        public ActionResult ExportToWord()
        {
            var list = new List<Item>();
            list.Add(new Item { Id=1});
            list.Add(new Item { Id = 2 });
            list.Add(new Item { Id = 3 });
            list.Add(new Item { Id = 4 });
            string htmlString = this.RenderRazorViewToString(@"Home\Index", list);

            Response.AddHeader("Content-Disposition", "filename=EFFReport.docx");
            Response.ContentType = "application/msword";
            Response.Write(htmlString);
            return null;
        }

        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

    }
}

MVCWeb/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWeb.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ReportInfo()
        {
            return View();
        }
    }
}

MVCWeb/Views/Default/DateModel.cshtml
@model  MVCWeb.Models.CustomerAccount
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DateModel</title>
</head>
<body>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div> 
        @Html.TextBoxFor(model => model.DOB, new { @Value = "dd/MM/yyyy" })

        @Html.ValidationMessageFor(model => model.DOB)
        
        
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

}
    
    @System.Threading.Thread.CurrentThread.CurrentCulture

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

MVCWeb/Views/Default/Edit.cshtml
@model  MVCWeb.Models.CustomerAccount
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @*// Hiding Buiness Data*@
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Yes").click(function () {

                $("#Comp_Info").show();
            });
            $("#No").click(function () {

                $("#Comp_Info").hide();


            });
        });
    </script>
    <meta name="viewport" content="width=device-width" />
    <title>RadioBtn</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Default",FormMethod.Post, new { id = "myForm" }))
 {
        @Html.ValidationSummary()
        @Html.HiddenFor(model => model.ID)

}
 // Personal Customer Data
 //-----------------------------------------------------------------------------------
<br />
        <b><strong> Customer Detail Information</strong></b>
        <br />
 //-----------------------------------------------------------------------------------
<br />

    <div style="font-family:Arial">
        <table>
            <tr>

                <td>

                    @Html.Label("Full Name :-*")
                    @Html.TextBoxFor(model => model.Full_Name , new { id = "name", name = "name" })<br />
                    <span id="nameError" class="error"></span><br />
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("Email :-*")
                    @*@Model.CustomerAccount.Email*@
                    @Html.TextBoxFor(model => model.Email,new { id = "email", name = "email" })<br />
                    <span id="emailError" class="error"></span><br />
                </td>
            </tr>

            <tr>

                <td>
                    // Checkbox to select if Buisness buisness or Personal Customer
                    @Html.Label("Customer Type :-")

                    @Html.RadioButtonFor(model => model.Is_Biz_Cust, false, new { @id = "No" })
                    @Html.Label("No", "Personal")
                    @Html.RadioButtonFor(model => model.Is_Biz_Cust, true, new { @id = "Yes" })
                    @Html.Label("Yes", "Business")

                </td>
            </tr>
        </table>
        
        // If this is true then show Buiness Customer otherwise only show Personal Customer
        
 // Buinsess Customer Data
            <div id="Comp_Info">
                <b><strong> Information</strong></b>
                <br />
                <br />
                @if (Model.Is_Biz_Cust.Equals(false))
                {
                @Html.Label("Company Name :-*")
                @Html.TextBoxFor(model => model.custdetail.Company_Name,new { id="cname",name="cname"})<br />


                @Html.Label("Email :-*")
                @Html.TextBoxFor(model => model.custdetail.Company_Email,new { id="cemail",name="cemail"})
                }
                <span id="cnameError" class="error"></span> <span id="cemailError" class="error"></span>
                <br />
                </div>
                

                <input type="submit" value="Save" name="@Url.Action("/Admin/Customer/index?%20&store_id=-1")" />

                }
                <p>
                    <a href="/Admin/Customer/index?%20&store_id=-1">Cancel</a>
                <p>
            @if (true)
            { 
                <p>hello true</p>
            }
            
        @if (false)
        { 
            <p>hellow false</p>
        }
    </body>
</html>

MVCWeb/Views/Default/Index.cshtml
@model IEnumerable<MVCWeb.Models.Item>

@{
    Layout = null;
}

<!DOCTYPE html>
<script type="text/javascript">
    //auto post checkbox
    function myFunction(id) {
        var status = document.getElementById("chkShow_" + id).checked;
        window.location.href = '/Default/updatevat?ID=' + id + '&status=' + status;
    }

    //auto post drobdownlist
    function mydropdown(id) {
        var discuount = document.getElementById("ddl" + id).select;
        //window.location.href = '/Default/updatdisc?ID=' + id + '&discuount=' + discuount;
    }
</script>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @foreach(var item in Model)
    { 
        //drobdownlist
        @Html.DropDownList("ddl" + item.Id, new SelectList(new[] { "1", "2", "3", "4", "5" }), new { onchange = "mydropdown(" + item.Id + ")" })

        //Checkbox

        if (true)
        {
        <p>

            @Html.CheckBox("check", new { id = "chkShow_" + item.Id, @checked = "checked", @class = "checker", @onchange = "myFunction(" + item.Id + ")" })
        </p>
        }
        else
        {
        <p>

            @Html.CheckBox("check", new { id = "chkShow_" + item.Id, @class = "checker", @onchange = "myFunction(" + item.Id + ")" });

        </p>
        }

    }
</head>
<body>
    <div> 

    </div>
</body>
</html>

MVCWeb/Views/Default/MainView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
@using MVCWeb.Helpers
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MainView</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script>
    $(document).ready(function () {
        $("#infopane").attr("src", '@Url.Action("ReportInfo", "Report")');
    });
    </script>
</head>
<body>
    <div id="mainSplitter">
        <div style="-ms-overflow-y: hidden; overflow-y: hidden; overflow-x: hidden; -ms-overflow-x: hidden;">
            <iframe id="infopane" src="" style="border-bottom: 0px;
border-left: 0px; border-top: 0px; border-right: 0px" frameborder="0"></iframe>
        </div>
        <div style="-ms-overflow-y: hidden; overflow-y: hidden; overflow-x: hidden; -ms-overflow-x: hidden;">
            <iframe id="searchpane" src="" style="border-bottom: 0px;
border-left: 0px; border-top: 0px; border-right: 0px" frameborder="0"></iframe>
        </div>
        <div>
            <label id="lab"></label>
            
        </div>
        <p>@ViewBag.SendCodeViewModel</p>
        <p>@ViewBag.SendCodeViewModel1</p>

        @Html.ContentBlock(new ISSCStyle() { color="Blue",Class="",Text="Hello World"});
        @*@Html.Partial("_MainViewPartialPage")*@
    </div>   
</body>
</html>

MVCWeb/Views/Default/_MainViewPartialPage.cshtml
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
            //your code here
            $('#ddlReports').on('change', function () {
            var val = $(this).val();
                var x = '@Url.Action("ReportSearch", "Report")' + "/" + val;
                alert(x);
                alert("hello");
                alert($("#searchpane1").length);
                alert($("#searchpane").name);
               

            });
        });
</script>
<div id="Reports">
    <span>Reports:</span> @Html.DropDownList("ddlReports", new List<SelectListItem>
{
new SelectListItem { Text = "Report1", Value = "1"},
new SelectListItem { Text = "Report2", Value = "2"},
new SelectListItem { Text = "Report3", Value = "3"}
}, "")
</div>
<div id="ReportInfo">
    @*@{
        Html.RenderPartial("ReportInfo");
        }*@
</div>

MVCWeb/Views/Default/addComment.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>addComment</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <div id="body">
        <p style="color:red"><strong>Hello Word</strong></p>

        @if (ViewBag.name != null)
        {            
          <script type="text/javascript">
              var x =@Html.Raw(Json.Encode(ViewBag.name));
              $("#body").append('<p>' + x + '</p>');
          </script>
        }
    </div>
   
    @Html.Partial("~/Views/Shared/_CommentPartial.cshtml")
</body>
</html>