MVCWeb/Controllers/EFHomeController.cs
using MVCWeb.DAL;
using MVCWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWeb.Controllers
{
    public class EFHomeController : Controller
    {
        private SchoolContext db = new SchoolContext();
        // GET: EFHome
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            IQueryable<EnrollmentDateGroup> data = from student in db.EFStudents
                                                   group student by student.EnrollmentDate into dategroup
                                                   select new EnrollmentDateGroup()
                                                   {
                                                       EnrollmentDate = dategroup.Key,
                                                       StudentCount = dategroup.Count()
                                                   };
            return View(data.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVCWeb/Views/EFHome/About.cshtml
@model IEnumerable<MVCWeb.ViewModels.EnrollmentDateGroup>

@{
    ViewBag.Title = "Student Body Statistics";
}

<h2>Student Body Statistics</h2>

<table>
    <tr>
        <th>
            Enrollment Date
        </th>
        <th>
            Students
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>
            <td>
                @item.StudentCount
            </td>
        </tr>
    }
</table>

MVCWeb/Views/EFHome/Index.cshtml
@{
    ViewBag.Title = "Index";   
}

<h2>Index</h2>

MVCWeb/Views/EFHome/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EFHome</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/modernizer")
</head>
<body>
    <div> 
        @Html.ActionLink("Contoso University","Index","EFHome")
        <div>
            <ul>
                <li>@Html.ActionLink("Home","Index","EFHome")</li>
                <li>@Html.ActionLink("About","About","EFHome")</li>
                <li>@Html.ActionLink("Students","Index","EFStudent")</li>
                <li>@Html.ActionLink("Courses","Index","EFCourse")</li>
                <li>@Html.ActionLink("Instructors", "Index", "EFInstructor")</li>
                <li>@Html.ActionLink("Departments", "Index", "EFDepartment")</li>
            </ul>
        </div>
    </div>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>